[package]
name = "tiervium"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5.8"
anyhow = "1.0.52"
mongodb = "2.1.0"

[dependencies.serde]
version = "1.0.133"
features = ["derive"]

[dependencies.tokio]
version = "1.15.0"
features = ["fs", "macros", "rt-multi-thread"]
