# Delay between scans in seconds
delay = 40

# API request timeout in seconds
timeout = 20

mysql = "mysql://user:pass@host/database"

# Tier API key
key = "bpEUTJEBTf74oGRWxaIcW7aeZMzDDODe1yBoSxi2"

# Zones to scan, comment out to scan all zones
zones = ["COLOGNE"]

[log]
level = "info"
style = "auto"
